### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by YihaoWEI** [wotchin/SmooFaceNet#1]
嗨！我最近也在想实现VIPLFaceNet，搜到您的代码，请问您使用的是ORL测试集吗（40人400脸）？效果如何？

**Comment by wotchin** [comment]
效果不错，这个实现的并不事VIPLFaceNet，是在他的基础上建立的网络，虽然这个数据集很小，容易出现过拟合，但是经过数据增强，在训练集上99.9%准确率，在测试集上约90%的准确率。

**Comment by YihaoWEI** [comment]
@wotchin Thanks! 我会持续关注您！
